language:
    - go

go:
    - "1.14.x"

env:
    - GO111MODULE=on

script:
    - go test -v  gosource/src/com.py/sourcego/sourceslice/*.go
    - go test -v -bench=. gosource/src/com.py/sourcego/sourceslice/*.go -benchtime=3s -run=none
